version: '3'
services:
  app:
    build: .
    ports:
      - "6000:6000"
    volumes:
      - .:/app
    command: ["npm", "start"]
    environment:
      - PORT
      - BASE_URL
      - DB_URL
      - JWT_SECRET
      - BCRYPT_SALT
